[2023-08-28T01:06:07.354+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gaas_etl_1.etl_event scheduled__2023-08-28T01:05:00+00:00 [queued]>
[2023-08-28T01:06:07.374+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gaas_etl_1.etl_event scheduled__2023-08-28T01:05:00+00:00 [queued]>
[2023-08-28T01:06:07.374+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-28T01:06:07.402+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): etl_event> on 2023-08-28 01:05:00+00:00
[2023-08-28T01:06:07.411+0000] {standard_task_runner.py:57} INFO - Started process 483866 to run task
[2023-08-28T01:06:07.431+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'gaas_etl_1', 'etl_event', 'scheduled__2023-08-28T01:05:00+00:00', '--job-id', '8108', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmp30mrmzzq']
[2023-08-28T01:06:07.438+0000] {standard_task_runner.py:85} INFO - Job 8108: Subtask etl_event
[2023-08-28T01:06:08.349+0000] {task_command.py:415} INFO - Running <TaskInstance: gaas_etl_1.etl_event scheduled__2023-08-28T01:05:00+00:00 [running]> on host data-system.us-central1-a.c.data-system-392010.internal
[2023-08-28T01:06:08.920+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hungnm15012002@gmail.com' AIRFLOW_CTX_DAG_OWNER='hungnm' AIRFLOW_CTX_DAG_ID='gaas_etl_1' AIRFLOW_CTX_TASK_ID='etl_event' AIRFLOW_CTX_EXECUTION_DATE='2023-08-28T01:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-28T01:05:00+00:00'
[2023-08-28T01:06:08.944+0000] {dag_etl.py:116} INFO - Extracting event...
[2023-08-28T01:06:09.243+0000] {extract.py:36} INFO - Request time: 0:00:00.298189
[2023-08-28T01:06:09.243+0000] {extract.py:45} ERROR - Server GAAS error: 502
[2023-08-28T01:06:09.251+0000] {dag_etl.py:119} INFO - Complete extract event: 0:00:00.306832
[2023-08-28T01:06:09.252+0000] {dag_etl.py:121} INFO - Transforming action...
[2023-08-28T01:06:09.254+0000] {dag_etl.py:149} ERROR - An Error Occur: object of type 'int' has no len()
[2023-08-28T01:06:09.254+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-08-28T01:06:09.268+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=gaas_etl_1, task_id=etl_event, execution_date=20230828T010500, start_date=20230828T010607, end_date=20230828T010609
[2023-08-28T01:06:09.329+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-28T01:06:09.353+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
