[2023-08-27T09:42:05.188+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gaas_etl_1.etl_user scheduled__2023-08-27T09:41:00+00:00 [queued]>
[2023-08-27T09:42:05.204+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gaas_etl_1.etl_user scheduled__2023-08-27T09:41:00+00:00 [queued]>
[2023-08-27T09:42:05.205+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-27T09:42:05.237+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): etl_user> on 2023-08-27 09:41:00+00:00
[2023-08-27T09:42:05.247+0000] {standard_task_runner.py:57} INFO - Started process 380888 to run task
[2023-08-27T09:42:05.263+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'gaas_etl_1', 'etl_user', 'scheduled__2023-08-27T09:41:00+00:00', '--job-id', '5335', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpfkt5zwb0']
[2023-08-27T09:42:05.269+0000] {standard_task_runner.py:85} INFO - Job 5335: Subtask etl_user
[2023-08-27T09:42:06.015+0000] {task_command.py:415} INFO - Running <TaskInstance: gaas_etl_1.etl_user scheduled__2023-08-27T09:41:00+00:00 [running]> on host data-system.us-central1-a.c.data-system-392010.internal
[2023-08-27T09:42:06.407+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hungnm15012002@gmail.com' AIRFLOW_CTX_DAG_OWNER='hungnm' AIRFLOW_CTX_DAG_ID='gaas_etl_1' AIRFLOW_CTX_TASK_ID='etl_user' AIRFLOW_CTX_EXECUTION_DATE='2023-08-27T09:41:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-27T09:41:00+00:00'
[2023-08-27T09:42:06.431+0000] {dag_etl.py:28} INFO - Extracting user...
[2023-08-27T09:42:14.537+0000] {extract.py:36} INFO - Request time: 0:00:08.105428
[2023-08-27T09:42:14.659+0000] {extract.py:42} INFO - Create DataFrame time: 0:00:00.121040
[2023-08-27T09:42:14.662+0000] {dag_etl.py:31} INFO - Complete extract user: 0:00:08.230580
[2023-08-27T09:42:14.662+0000] {dag_etl.py:33} INFO - Extracting resource...
[2023-08-27T09:42:15.172+0000] {extract.py:36} INFO - Request time: 0:00:00.509979
[2023-08-27T09:42:15.173+0000] {extract.py:45} ERROR - Server GAAS error: 502
[2023-08-27T09:42:15.179+0000] {dag_etl.py:36} INFO - Complete extract resource: 0:00:00.517764
[2023-08-27T09:42:15.180+0000] {dag_etl.py:38} INFO - Transforming user...
[2023-08-27T09:42:15.183+0000] {dag_etl.py:107} ERROR - An Error Occur: Can only merge Series or DataFrame objects, a <class 'int'> was passed
[2023-08-27T09:42:15.190+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-08-27T09:42:15.206+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=gaas_etl_1, task_id=etl_user, execution_date=20230827T094100, start_date=20230827T094205, end_date=20230827T094215
[2023-08-27T09:42:15.269+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-27T09:42:15.296+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
