[2023-08-27T16:02:06.456+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gaas_etl_1.etl_event scheduled__2023-08-27T16:01:00+00:00 [queued]>
[2023-08-27T16:02:06.488+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gaas_etl_1.etl_event scheduled__2023-08-27T16:01:00+00:00 [queued]>
[2023-08-27T16:02:06.488+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-27T16:02:06.537+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): etl_event> on 2023-08-27 16:01:00+00:00
[2023-08-27T16:02:06.556+0000] {standard_task_runner.py:57} INFO - Started process 426663 to run task
[2023-08-27T16:02:06.577+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'gaas_etl_1', 'etl_event', 'scheduled__2023-08-27T16:01:00+00:00', '--job-id', '6477', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpge3wamlk']
[2023-08-27T16:02:06.590+0000] {standard_task_runner.py:85} INFO - Job 6477: Subtask etl_event
[2023-08-27T16:02:07.363+0000] {task_command.py:415} INFO - Running <TaskInstance: gaas_etl_1.etl_event scheduled__2023-08-27T16:01:00+00:00 [running]> on host data-system.us-central1-a.c.data-system-392010.internal
[2023-08-27T16:02:08.134+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hungnm15012002@gmail.com' AIRFLOW_CTX_DAG_OWNER='hungnm' AIRFLOW_CTX_DAG_ID='gaas_etl_1' AIRFLOW_CTX_TASK_ID='etl_event' AIRFLOW_CTX_EXECUTION_DATE='2023-08-27T16:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-27T16:01:00+00:00'
[2023-08-27T16:02:08.150+0000] {dag_etl.py:116} INFO - Extracting event...
[2023-08-27T16:02:08.442+0000] {extract.py:36} INFO - Request time: 0:00:00.291074
[2023-08-27T16:02:08.442+0000] {extract.py:45} ERROR - Server GAAS error: 502
[2023-08-27T16:02:08.450+0000] {dag_etl.py:119} INFO - Complete extract event: 0:00:00.300252
[2023-08-27T16:02:08.451+0000] {dag_etl.py:121} INFO - Transforming action...
[2023-08-27T16:02:08.454+0000] {dag_etl.py:149} ERROR - An Error Occur: object of type 'int' has no len()
[2023-08-27T16:02:08.455+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-08-27T16:02:08.467+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=gaas_etl_1, task_id=etl_event, execution_date=20230827T160100, start_date=20230827T160206, end_date=20230827T160208
[2023-08-27T16:02:08.531+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-27T16:02:08.555+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
