[2023-08-27T16:53:07.124+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gaas_etl_1.etl_user scheduled__2023-08-27T16:52:00+00:00 [queued]>
[2023-08-27T16:53:07.143+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gaas_etl_1.etl_user scheduled__2023-08-27T16:52:00+00:00 [queued]>
[2023-08-27T16:53:07.144+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-27T16:53:07.175+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): etl_user> on 2023-08-27 16:52:00+00:00
[2023-08-27T16:53:07.187+0000] {standard_task_runner.py:57} INFO - Started process 432056 to run task
[2023-08-27T16:53:07.201+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'gaas_etl_1', 'etl_user', 'scheduled__2023-08-27T16:52:00+00:00', '--job-id', '6629', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpoe0g04bo']
[2023-08-27T16:53:07.207+0000] {standard_task_runner.py:85} INFO - Job 6629: Subtask etl_user
[2023-08-27T16:53:08.098+0000] {task_command.py:415} INFO - Running <TaskInstance: gaas_etl_1.etl_user scheduled__2023-08-27T16:52:00+00:00 [running]> on host data-system.us-central1-a.c.data-system-392010.internal
[2023-08-27T16:53:08.765+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hungnm15012002@gmail.com' AIRFLOW_CTX_DAG_OWNER='hungnm' AIRFLOW_CTX_DAG_ID='gaas_etl_1' AIRFLOW_CTX_TASK_ID='etl_user' AIRFLOW_CTX_EXECUTION_DATE='2023-08-27T16:52:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-27T16:52:00+00:00'
[2023-08-27T16:53:08.797+0000] {dag_etl.py:28} INFO - Extracting user...
[2023-08-27T16:53:21.930+0000] {extract.py:36} INFO - Request time: 0:00:13.132825
[2023-08-27T16:53:22.582+0000] {extract.py:42} INFO - Create DataFrame time: 0:00:00.651430
[2023-08-27T16:53:22.587+0000] {dag_etl.py:31} INFO - Complete extract user: 0:00:13.790670
[2023-08-27T16:53:22.588+0000] {dag_etl.py:33} INFO - Extracting resource...
[2023-08-27T16:53:23.094+0000] {extract.py:36} INFO - Request time: 0:00:00.506030
[2023-08-27T16:53:23.095+0000] {extract.py:45} ERROR - Server GAAS error: 502
[2023-08-27T16:53:23.103+0000] {dag_etl.py:36} INFO - Complete extract resource: 0:00:00.515034
[2023-08-27T16:53:23.104+0000] {dag_etl.py:38} INFO - Transforming user...
[2023-08-27T16:53:23.108+0000] {dag_etl.py:107} ERROR - An Error Occur: Can only merge Series or DataFrame objects, a <class 'int'> was passed
[2023-08-27T16:53:23.136+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-08-27T16:53:23.148+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=gaas_etl_1, task_id=etl_user, execution_date=20230827T165200, start_date=20230827T165307, end_date=20230827T165323
[2023-08-27T16:53:23.198+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-27T16:53:23.219+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
