[2023-08-27T15:24:06.423+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gaas_etl_1.etl_user scheduled__2023-08-27T15:23:00+00:00 [queued]>
[2023-08-27T15:24:06.440+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gaas_etl_1.etl_user scheduled__2023-08-27T15:23:00+00:00 [queued]>
[2023-08-27T15:24:06.441+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-27T15:24:06.467+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): etl_user> on 2023-08-27 15:23:00+00:00
[2023-08-27T15:24:06.478+0000] {standard_task_runner.py:57} INFO - Started process 422624 to run task
[2023-08-27T15:24:06.495+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'gaas_etl_1', 'etl_user', 'scheduled__2023-08-27T15:23:00+00:00', '--job-id', '6363', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmp3a69m1z3']
[2023-08-27T15:24:06.500+0000] {standard_task_runner.py:85} INFO - Job 6363: Subtask etl_user
[2023-08-27T15:24:07.307+0000] {task_command.py:415} INFO - Running <TaskInstance: gaas_etl_1.etl_user scheduled__2023-08-27T15:23:00+00:00 [running]> on host data-system.us-central1-a.c.data-system-392010.internal
[2023-08-27T15:24:08.408+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hungnm15012002@gmail.com' AIRFLOW_CTX_DAG_OWNER='hungnm' AIRFLOW_CTX_DAG_ID='gaas_etl_1' AIRFLOW_CTX_TASK_ID='etl_user' AIRFLOW_CTX_EXECUTION_DATE='2023-08-27T15:23:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-27T15:23:00+00:00'
[2023-08-27T15:24:08.430+0000] {dag_etl.py:28} INFO - Extracting user...
[2023-08-27T15:24:08.962+0000] {extract.py:36} INFO - Request time: 0:00:00.530631
[2023-08-27T15:24:08.962+0000] {extract.py:45} ERROR - Server GAAS error: 502
[2023-08-27T15:24:08.975+0000] {dag_etl.py:31} INFO - Complete extract user: 0:00:00.545246
[2023-08-27T15:24:08.977+0000] {dag_etl.py:33} INFO - Extracting resource...
[2023-08-27T15:24:11.219+0000] {extract.py:36} INFO - Request time: 0:00:02.242258
[2023-08-27T15:24:11.302+0000] {extract.py:42} INFO - Create DataFrame time: 0:00:00.082333
[2023-08-27T15:24:11.304+0000] {dag_etl.py:36} INFO - Complete extract resource: 0:00:02.328914
[2023-08-27T15:24:11.305+0000] {dag_etl.py:38} INFO - Transforming user...
[2023-08-27T15:24:11.309+0000] {dag_etl.py:107} ERROR - An Error Occur: 'int' object has no attribute 'merge'
[2023-08-27T15:24:11.311+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-08-27T15:24:11.324+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=gaas_etl_1, task_id=etl_user, execution_date=20230827T152300, start_date=20230827T152406, end_date=20230827T152411
[2023-08-27T15:24:11.371+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-27T15:24:11.397+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
